function setTriggers () {
    for (let index = 0; index <= 3; index++) {
        tiles.setTileAt(tiles.getTileLocation(index * 4 + 2, array_wrong_way[index] * 5 + 1), assets.tile`BlackTilwe`)
        tiles.setTileAt(tiles.getTileLocation(index * 4 + 2, array_wrong_way[index] * 5 + 2), assets.tile`BlackTilwe`)
    }
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`BlackTilwe`, function (sprite, location) {
    tempX = (mySprite.x + 32) / 16
    for (let value of list) {
        tiles.setWallAt(tiles.getTileLocation(tempX, value), true)
        tiles.setTileAt(tiles.getTileLocation(tempX, value), sprites.builtin.brick)
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.swamp.swampTile9, function (sprite, location) {
    if (mySprite.x > 80) {
        game.over(true)
    } else {
        for (let index = 0; index <= 16; index++) {
            for (let value of list) {
                tiles.setWallAt(tiles.getTileLocation(index, value), false)
                tiles.setTileAt(tiles.getTileLocation(index, value), assets.tile`transparency16`)
            }
        }
        setTriggers()
    }
})
let tempX = 0
let list: number[] = []
let array_wrong_way: number[] = []
let mySprite: Sprite = null
game.showLongText("Move the Heart to the purple box on the right. If you get stuck go back to the purple box on the left and try again with the same walls. each time you restart the game the walls change.", DialogLayout.Full)
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .......22...22......
    ......2322.2222.....
    ......232222222.....
    ......222222222.....
    .......22222b2......
    ........222b2.......
    .........222........
    ..........2.........
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
array_wrong_way = [0, 1, 0, 0]
for (let index = 0; index <= 3; index++) {
    array_wrong_way[index] = randint(0, 1)
}
setTriggers()
tiles.placeOnTile(mySprite, tiles.getTileLocation(0, 4))
controller.moveSprite(mySprite, 100, 100)
scene.cameraFollowSprite(mySprite)
list = [1, 2, 6, 7]
